site_name: Documentación de CNAUTA
site_description: Documentación de la aplicación CNAUTA, que permite a los usuarios interactuar fácilmente con el portal Nauta de Etecsa.
site_author: mamei

# use_directory_urls: false
# repo_url: https://github.com/delineas/mkdocs-demo/

nav:
  - Inicio: index.md
  # - Secciones importantes:
      # - Partes del sistema: section/partes_sistema.md
#  - Manual del usuario: section/tutorial.md
  - Glosario: glossary.md
  - ¿Quienes somos?: about.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

# plugins:
#   - mermaid2
#   # - search
#   # - pdf-export

site_url: http://127.0.0.1/

theme:
  name: material
  # name: readthedocs
  language: es

extra:
  alternate:
    # Switch to English
    - name: English
      link: /en/
      lang: en

    # Switch to Spanish
    - name: Español
      link: /es/
      lang: es

# extra_javascript:
#     - https://unpkg.com/mermaid/dist/mermaid.min.js

plugins:
  - search:
      lang: en                                      # Set language for search